### ISSUE TITLE
Show "loading..." when refreshing programs

### ISSUE THREAD

**Issue by Jelmerro** [PilatusDevs/StatusPilatus#15]
It seems I have not included this in my pull request, which has already been merged. The request is to empty the list when the refresh button is pressed, and to show a "loading..." message as long as the list is still loading. It's not essential, but it's a nice to have @fabiaant will fix soon:tm:.

**Comment by fabiaant** [comment]
Since the loading of programs is rather slow on Windows, I've also noticed that the refresh button is not disabled during the first load. I'll pick this up as soon as possible and I'll try to give the refresh button a nice animation while I'm at it :)
