### ISSUE TITLE
Scrollbars in the sidebar

### ISSUE THREAD

**Issue by Jelmerro** [PilatusDevs/StatusPilatus#26]
## Expected Behavior
I should not have a horizontal scrollbar in the sidebar.

## Actual Behavior
When resizing the window to a size that needs a vertical scrollbar, a horizontal scrollbar will be displayed as well, even though the width of the sidebar stays the same.

## Possible Solution
Disable the horizontal scrollbar entirely for the sidebar and only display the vertical scrollbar.

## Steps to Reproduce (for bugs)
1. Resize the window to be shorter than the sidebar
2. Now there is a useless horizontal scrollbar

**Comment by lmeikle** [comment]
pull request made https://github.com/PilatusDevs/StatusPilatus/pull/27
