### ISSUE TITLE
Disk size

### ISSUE THREAD

**Issue by MeesMaas** [PilatusDevs/StatusPilatus#4]
## Expected Behavior
Total disk size not correct

## Actual Behavior
Not doing it

## Possible Solution
Contact that other dude

## Steps to Reproduce (for bugs)
1. Have linux or windows

## Context
I feel unsafe

## Your Environment
Include as many relevant details about the environment you experienced the bug in
* Version used: latest
* Operating System and version (desktop or mobile): desktop
* NodeJs version latest
* Npm version latest

**Comment by Jelmerro** [comment]
I do not have this issue with linux, and have tested this on a couple of windows machines without problems. The only problem I have found is that the disk usage is not supported on windows by systeminformation, which has already been requested here https://github.com/sebhildebrandt/systeminformation/issues/138. The disk storage part has always worked on all the machines I have tried recently. I'm going to close this issue, if this is still a problem, please add better steps to reproduce and more information about the actual issue.
