### ISSUE TITLE
Use Materialize instead of Bootstrap

### ISSUE THREAD

**Issue by M4Yt** [PilatusDevs/StatusPilatus#47]
## Design decision
Since we will not be updating Bootstrap, we want to move to Materialize. We will need to tweak some HTML and CSS.

**Comment by Jelmerro** [comment]
I agree to this change, I think it should indeed be fixed before 1.0.0 :+1:

**Comment by Jelmerro** [comment]
I will probably start working on this at the end of this week, shortly after the 0.5.0 release is done.

**Comment by M4Yt** [comment]
Moving away from Bootstrap 3 also means losing Glyphicons, I propose adding [Material Icons](https://www.npmjs.com/package/material-icons), as it fits Materialize quite well.
