### ISSUE TITLE
GPU(s) keep getting added to list

### ISSUE THREAD

**Issue by M4Yt** [PilatusDevs/StatusPilatus#48]
## Expected Behavior
Each GPU is added to the list of GPUs once.

## Actual Behavior
GPUs can be added to the list multiple times.
![pastedimage 1](https://user-images.githubusercontent.com/8672067/51495521-f734ca80-1dbc-11e9-935f-15760081ef76.png)

## Possible Solution
Make sure the same GPUs don't get added again by setting the saved array to the result instead of adding to the array, or check to see if the function was already activated.

## Steps to Reproduce (for bugs)
Providing your machine is slow enough, you'll be able to click the GPU tab multiple times before the GPU data is loaded, this is what causes a function to trigger multiple times.

**Comment by MeesMaas** [comment]
Spamming the GPU button for the first time after StatusPilatus is launched also reproduces this bug
