### ISSUE TITLE
Memory tab graph

### ISSUE THREAD

**Issue by MeesMaas** [PilatusDevs/StatusPilatus#5]
## Expected Behavior
Work as the other graphs

## Actual Behavior
Not doing it

## Possible Solution
Write some other code

## Steps to Reproduce (for bugs)
 Provide an unambiguous set of steps to reproduce this bug.  
 Include code to reproduce, if relevant.
1. Click on the network tab
2.
3.
4.

## Context
\#metoo

**Comment by Jelmerro** [comment]
To explain this issue in a bit more detail:
The memory graph is reset when moving between pages, whereas the other graphs keep the data intact when switching back.
